baseURL = 'https://bittientakana.blog/'
languageCode = 'fi-fi'
theme = 'hugo-bearblog'
title = 'Bittien takana'
enableRobotsTXT = true
rssLimit = 20

[author]
  name = "Antti Ajanki"
  email = "antti.ajanki@iki.fi"

[taxonomies]
  tag = 'tags'

[params]
  # The "description" of your website. This is used in the meta data of your generated html.
  #description = "Hugo + Bear = :heart:"

  favicon = "favicon.png"

  # These "images" are used for the structured data templates. This will show up, when
  # services like Twitter or Slack want to generate a preview of a link to your site.
  # See https://gohugo.io/templates/internal#twitter-cards and
  # https://gohugo.io/templates/internal#open-graph.
  #images = ["images/share.png"]

  title = "Bittien takana"

  dateFormat = "2.1.2006"
